<Project>
    <PropertyGroup>
        <Version>0.0.2</Version>
        <Authors>BepInEx,Nexr-Fast</Authors>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
        <DebugType>embedded</DebugType>
        <Configurations>Debug;Release;PreRelease</Configurations>
        <PackageProjectUrl>https://github.com/Next-Fast/NextBepLoader</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Next-Fast/NextBepLoader</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>logo.png</PackageIcon>
        <OutDir>$(SolutionDir)Output\Build</OutDir>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <NoWarn>CS8618;NU5104</NoWarn>
        <PackageOutputPath>$(SolutionDir)Output\Package</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' != 'Debug'">
        <None Include="$(SolutionDir)assets\logo.png" Pack="true" PackagePath="\" />
        <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <!-- CopyLocalLockFileAssemblies causes to also output shared assemblies: https://github.com/NuGet/Home/issues/4837#issuecomment-354536302 -->
    <!-- Since all core assemblies usually follow naming of System.*, we just delete them for now -->
    <!-- Also delete deps.json as they are not used by mono -->
    <Target Name="DeleteSys" AfterTargets="Build">
        <ItemGroup>
            <FilesToDelete Include="$(OutputPath)System.*.dll"/>
            <FilesToDelete Include="$(OutputPath)*.deps.json"/>
        </ItemGroup>
        <Delete Files="@(FilesToDelete)"/>
    </Target>
</Project>
