<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Core classes and utilities for BepInEx Preloader</Description>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>NextBepLoader.Core.PreLoader</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NextBepLoader.Core\NextBepLoader.Core.csproj"/>
        
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All"/>
        <PackageReference Include="HarmonyX" Version="2.14.0" />
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.2.3" />
        <PackageReference Include="MonoMod.Utils" Version="25.0.8" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    </ItemGroup>
</Project>
