name: CI

on:
    push:
        branches: [ Next ]
        paths:
            - '**/*.csproj'
            - '.github/workflows/main.yml'
            - 'Directory.Build.props'

jobs:
    build-Destop:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'Next-Fast'
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/cache@v3
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 9.x

            - name: Build
              run: dotnet build -c PreRelease --version-suffix ci.${{ github.run_number }}
            
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                  name: Desktop-Build
                  path: ./Output/Build/
            
            - name: Upload Package
              uses: actions/upload-artifact@v4
              with:
                  name: Desktop-Package
                  path: ./Output/Package/
            
            - name: Push to Nuget
              run: |
                dotnet nuget push ./Output/Package/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETKEY }}
